version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "8080:8080"
    volumes:
      - "./app:/app"
    command: bash -c 'sleep 3 && npm start'

  caddy:
    image: caddy:2.4.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./caddy_data:/data"
      - "./caddy_config:/config"
    depends_on:
      - app
volumes:
  caddy_data:
  caddy_config: