version: "3"
services:
  app:
    image: solxun/devops-for-programmers-project-lvl1
    build:
      context: app
      dockerfile: Dockerfile
    command: bash -c 'sleep 3 && make test'
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password